### ISSUE TITLE
请问使用的是原始数据集里面的那个文件呀？刚开始做研究不理解，谢谢

### ISSUE THREAD

**Issue by zulianal** [imfaisalmalik/CTU13-CSV-Dataset#1]

**Comment by zulianal** [comment]
怎么提取数据集的异常流量和正常流量呢？

**Comment by imfaisalmalik** [comment]
Hey! Here are the answers to your queries:

**How to extract the abnormal traffic and normal traffic of the data set?**
Download the following 2 files from my [Github Repo](https://github.com/imfaisalmalik/CTU13-CSV-Dataset/)

- CTU13_Attack_Traffic.csv contains Botnet attack traffic samples.
- CTU13_Normal_Traffic.csv contains Normal traffic samples.
	
**How to extract data set of abnormal flow and normal flow?**
If you want to extract abnormal flow and normal flow yourself, then go to [CTU13 website](https://www.stratosphereips.org/datasets-ctu13), from there you can access each scenario's Pcap file individually
	-
